[package]
name = "triangel"
version = "0.1.0"
authors = ["ParoRahul <r.das699@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
rand = "0.8.3"
crossterm = "0.19.0"
